import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       
        <Navbar/>
         {children}
        <Footer/>
        </body>
    </html>
  );
}
// import { Cairo } from "next/font/google";

// const cairo = Cairo({
//   subsets: ["arabic"],
//   weight: ["400", "600", "700", "900"],
//   variable: "--font-cairo",
// });

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="ar" dir="rtl" className={cairo.variable}>
//       <body className={`${cairo.className} bg-[#f8fafc]`}>{children}</body>
//     </html>
//   );
// }